#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.2 on Wed Jul 14 00:46:31 2021
#

import wx


# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class ChessClassicFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ChessClassicFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1000, 750))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_1.Add((0, 0), 0, 0, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        # end wxGlade


# end of class ChessClassicFrame

class ChessClassicApplication(wx.App):
    def OnInit(self):
        self.frame = ChessClassicFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True


# end of class ChessClassicApplication

if __name__ == "__main__":
    application = ChessClassicApplication(0)
    application.MainLoop()
