# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.2 on Fri Jul 16 00:25:51 2021
#

import wx




class BaseMenuFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetTitle("frame")

        self.panel = wx.Panel(self, wx.ID_ANY)

        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)

        sizer_7.Add((50, 0), 0, wx.EXPAND, 0)

        sizer_8 = wx.BoxSizer(wx.VERTICAL)
        sizer_7.Add(sizer_8, 1, wx.EXPAND, 0)

        sizer_8.Add((0, 50), 0, 0, 0)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_8.Add(sizer_2, 0, wx.EXPAND, 0)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_3, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 0)

        label_1 = wx.StaticText(self.panel, wx.ID_ANY, "Variant:")
        sizer_3.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        sizer_3.Add((5, 0), 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.variant_combo_box = wx.ComboBox(self.panel, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        sizer_3.Add(self.variant_combo_box, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        static_line_1 = wx.StaticLine(self.panel, wx.ID_ANY)
        sizer_2.Add(static_line_1, 0, wx.ALL | wx.EXPAND, 15)

        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_10, 1, wx.EXPAND, 0)

        sizer_10.Add((50, 0), 0, 0, 0)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_10.Add(sizer_1, 1, wx.BOTTOM | wx.EXPAND | wx.TOP, 5)

        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_4, 1, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_2 = wx.StaticText(self.panel, wx.ID_ANY, "Total Time (Minutes):")
        sizer_4.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        sizer_4.Add((5, 0), 0, 0, 0)

        self.total_time_ctrl = wx.TextCtrl(self.panel, wx.ID_ANY, "")
        sizer_4.Add(self.total_time_ctrl, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.total_time_slider = wx.Slider(self.panel, wx.ID_ANY, 0, 0, 10)
        sizer_1.Add(self.total_time_slider, 0, wx.EXPAND, 0)

        sizer_1.Add((0, 10), 0, 0, 0)

        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_5, 1, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_3 = wx.StaticText(self.panel, wx.ID_ANY, "Increment Time (Seconds):")
        sizer_5.Add(label_3, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        sizer_5.Add((5, 0), 0, 0, 0)

        self.increment_time_ctrl = wx.TextCtrl(self.panel, wx.ID_ANY, "")
        sizer_5.Add(self.increment_time_ctrl, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.increment_time_slider = wx.Slider(self.panel, wx.ID_ANY, 0, 0, 10)
        sizer_1.Add(self.increment_time_slider, 0, wx.ALL | wx.EXPAND, 0)

        sizer_1.Add((0, 10), 0, 0, 0)

        self.side_radio_box = wx.RadioBox(self.panel, wx.ID_ANY, "Side:", choices=["Random", "Black", "White"], majorDimension=1, style=wx.RA_SPECIFY_ROWS)
        self.side_radio_box.SetSelection(0)
        sizer_1.Add(self.side_radio_box, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        sizer_10.Add((50, 0), 0, 0, 0)

        static_line_2 = wx.StaticLine(self.panel, wx.ID_ANY)
        sizer_2.Add(static_line_2, 0, wx.ALL | wx.EXPAND, 15)

        self.play_button = wx.Button(self.panel, wx.ID_ANY, "Play")
        sizer_2.Add(self.play_button, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        sizer_2.Add((0, 50), 0, 0, 0)

        sizer_7.Add((50, 0), 0, wx.EXPAND, 0)

        self.panel.SetSizer(sizer_7)

        sizer_7.Fit(self)
        self.Layout()


class BaseGameFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_1.Add((0, 0), 0, 0, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

